spring.application.name=phonebook

# Adatbázis kapcsolat
spring.datasource.url=jdbc:mysql://localhost:3306/phonebook_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# A Spring Boot automatikusan hozza létre/frissítse a táblákat a kódunk alapján
spring.jpa.hibernate.ddl-auto=update